site_name: Harbor.dev
site_url: https://harbor.dev
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
plugins:
    - awesome-pages
    - search

